server:
  port: 8081

spring:
  datasource:
    username: monitoring
    password: monitoringPw
    url: jdbc:mariadb://localhost:23306/monitoring

camunda:
  bpm:
    database:
      type: mysql
      schema-update: true