server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  datasource:
    username: orders
    password: ordersPw
    url: jdbc:mariadb://localhost:33306/orders