server:
  port: 8083

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  datasource:
    username: invoices
    password: invoicesPw
    url: jdbc:mariadb://localhost:13306/invoices
